version: '3.8'

services:
  cross-compile:
    build: .
    container_name: cross-compile

    # Allow attaching to the container.
    stdin_open: true
    tty: true

    # Required to allow fuse and sshfs to work.
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse

    volumes:
      # Mount local user's SSH key into container.
      - ~/.ssh/id_ed25519:/root/.ssh/id_ed25519:ro
